void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int myFunction(int n, int sq);
int is_prime_number(int n);
int prime_number_checker(int divider, int n);
int is_palindrome(char *s);
int palindrome_length(char *s);
int check_palindrome(char *s, int l);
int wildcmp(char *s1, char *s2);
